default-target = "wasm32-unknown-emscripten"

[target.emscripten]
link-args = ["-s", "USE_SDL=2", "-s", "ALLOW_MEMORY_GROWTH=1", "-s", "NO_EXIT_RUNTIME=1", "-s", "ASSERTIONS=2", "-s", "SAFE_HEAP=1", "-s", "BINARYEN_TRAP_MODE='clamp'", "-s", "DISABLE_EXCEPTION_CATCHING=0", "-s", "WASM=1", "-s", "WARN_UNALIGNED=1", "-s", "DEMANGLE_SUPPORT=1"]
